services:
  - type: web
    name: fixion-backend
    env: node
    region: oregon
    rootDir: backend
    buildCommand: yarn && yarn build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
